global:
    settings:
        dinkly_version: "2.33"
        time_format: h:i a
        languages:
            english:
                - en
                - en_US
            french: 
                - fr
                - fr_FR
                - fr_CA

    plugins:
        mini_ticket:
            apps:
                mini_ticket_admin:
                    app_name: MiniTicketAdmin
                    is_plugin: true
                    base_href: /ticket
                    enabled: true
                    default_module: home
        image_resizer:
            apps:
                image:
                    app_name: Handler
                    is_plugin: true
                    base_href: /image
                    enabled: true
                    default_module: handler
                    files_directory: uploads

    apps:
        frontend:
            default_app: true
            default_module: landing
            enabled: true
            base_href: /
            app_name: Habitat
            app_description: A UVM-authenticated to help people find roommates.
        user:
            default_module: home
            base_href: /user
            enabled: true
            app_name: Habitat - user
            app_description: Find a roommate for next year!
        admin:
            default_module: home
            base_href: /admin
            enabled: false
            app_name: Dinkly Admin
            app_description: Admin for the humblest little MVC
            copyright: Dinkly
            current_app_url: http://localhost:8888
        api:
            app_name: Dinkly API
            base_href: /api
            enabled: true
            default_module: api
        doc:
            app_name: Dinkly Documentation
            base_href: /doc
            default_module: home
            enabled: true

    databases:
        habitat:
            host: webdb.uvm.edu
            user: jsiebert_admin
            pass: 3RKXrrppFQevYdcr
            name: JSIEBERT_habitat

        dinkly:
            host: webdb.uvm.edu
            user: jsiebert_admin
            pass: 3RKXrrppFQevYdcr
            name: JSIEBERT_habitat_admin

        mini_ticket:
            host: localhost
            user: root
            pass: root
            name: dinkly_app

        unit_test:
            host: localhost
            user: root
            pass: root
            name: dinkly_unit_test
dev:
    settings:
    apps:
        admin:
            app_name: Dinkly Admin Dev
live:
    settings:
    apps:
        admin:
            app_name: Dinkly Admin Dev
