global:
    settings:
        dinkly_version: "2.33"
        time_format: h:i a
        languages:
            english:
                - en
                - en_US
            french: 
                - fr
                - fr_FR
                - fr_CA

    plugins:
        mini_ticket:
            apps:
                mini_ticket_admin:
                    app_name: MiniTicketAdmin
                    is_plugin: true
                    base_href: /ticket
                    enabled: true
                    default_module: home
        image_resizer:
            apps:
                image:
                    app_name: Handler
                    is_plugin: true
                    base_href: /image
                    enabled: true
                    default_module: handler
                    files_directory: uploads

    apps:
        frontend:
            default_app: true
            default_module: landing
            enabled: true
            base_href: /
            app_name: Habitat - Find a UVM roommate!
            app_description: An app to help you find a compatible roommate at UVM
        user:
            default_module: home
            enabled: true
            base_href: /user
            app_name: Habitat
            app_description: You can do better than a rando!
        admin:
            default_module: home
            base_href: /admin
            enabled: true
            app_name: Dinkly Admin
            app_description: Admin for the humblest little MVC
            copyright: Dinkly
            current_app_url: http://localhost:8888
        api:
            app_name: Dinkly API
            base_href: /api
            enabled: true
            default_module: api
        doc:
            app_name: Dinkly Documentation
            base_href: /doc
            default_module: home
            enabled: true

    databases:
        habitat:
            host: 127.0.0.1:8889
            user: root
            pass: root
            name: habitat
        dinkly:
            host: 127.0.0.1:8889
            user: root
            pass: root
            name: dinkly_app
        mini_ticket:
            host: 127.0.0.1:8889
            user: root
            pass: root
            name: dinkly_app
        unit_test:
            host: 127.0.0.1:8889
            user: root
            pass: root
            name: dinkly_unit_test

dev:
    settings:
    apps:
        admin:
            app_name: Dinkly Admin Dev
live:
    settings:
    apps:
        admin:
            app_name: Dinkly Admin Dev
